#!/bin/bash -e

trap 'echo $PWD/$0' ERR
{
  /bin/true --version --help
  /bin/true --version --version
  /bin/true x y
} >out 2>err
[[ ! -s out ]]
[[ ! -s err ]]
rm out err # retain bad output on failure
